import { supabase, OWNER_EMAIL } from '../supabase-config.js';

const loginView = document.querySelector('#login-view'); const studioView = document.querySelector('#studio-view');
const loginForm = document.querySelector('#login-form'); const editor = document.querySelector('#editor'); const nav = document.querySelector('#post-nav');
const state = document.querySelector('#save-state'); const deleteButton = document.querySelector('#delete-post');
let user = null; let posts = []; let currentId = null; let dirty = false; let saveTimer = null;
const field = name => editor.elements[name];
const slugify = text => text.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,150);
const esc = value => String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

loginForm.addEventListener('submit', async event => { event.preventDefault(); const message = loginForm.querySelector('.form-message'); message.textContent = 'Memeriksa akun…'; const values = new FormData(loginForm); const { data, error } = await supabase.auth.signInWithPassword({email:values.get('email'),password:values.get('password')}); if (error) { message.textContent = 'Email atau password belum cocok.'; return; } if (data.user.email?.toLowerCase() !== OWNER_EMAIL) { await supabase.auth.signOut(); message.textContent = 'Akun ini tidak memiliki akses ke Studio.'; return; } await openStudio(data.user); });

document.querySelector('#activate-account').addEventListener('click', async () => {
  const message = loginForm.querySelector('.form-message'); const password = loginForm.elements.password.value;
  if (password.length < 8) { message.textContent = 'Buat password minimal 8 karakter terlebih dahulu.'; return; }
  message.textContent = 'Membuat akun Studio…';
  const { data, error } = await supabase.auth.signUp({ email: OWNER_EMAIL, password, options: { emailRedirectTo: `${location.origin}/studio/` } });
  if (error) { message.textContent = error.message; return; }
  if (data.session) await openStudio(data.user); else message.textContent = 'Cek email Dicky untuk konfirmasi akun, lalu kembali dan login di sini.';
});

async function openStudio(activeUser) { user = activeUser; loginView.classList.add('hidden'); studioView.classList.remove('hidden'); await loadPosts(); if (!currentId) newPost(); }
async function loadPosts(selectId = currentId) { const { data, error } = await supabase.from('blog_posts').select('*').order('updated_at',{ascending:false}); if (error) { state.textContent = 'Gagal memuat tulisan'; return; } posts = data || []; nav.innerHTML = posts.map(post => `<button class="nav-post ${post.id===selectId?'active':''}" data-id="${post.id}"><strong>${esc(post.title || 'Tanpa judul')}</strong><span>${post.status} · ${post.access_level==='password'?'terkunci':'publik'}</span></button>`).join('') || '<span style="padding:12px;color:rgba(255,255,255,.45);font-size:.75rem">Belum ada tulisan.</span>'; }

function newPost() { currentId = null; editor.reset(); field('category').value = 'Catatan'; field('status').value = 'draft'; field('access_level').value = 'public'; field('cover_url').value = ''; document.querySelector('#cover-preview').classList.add('hidden'); deleteButton.classList.add('hidden'); toggleFields(); state.textContent = 'Tulisan baru'; dirty = false; loadPosts(null); }
function loadPost(id) { const post = posts.find(item => item.id===id); if (!post) return; currentId=id; ['title','subtitle','slug','excerpt','category','content','cover_url'].forEach(name => field(name).value=post[name]||''); field('tags').value=(post.tags||[]).join(', '); field('status').value=post.status; field('access_level').value=post.access_level; field('article_password').value=''; field('published_at').value=post.published_at ? new Date(new Date(post.published_at).getTime()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16) : ''; const preview=document.querySelector('#cover-preview'); if(post.cover_url){preview.src=post.cover_url;preview.classList.remove('hidden')}else preview.classList.add('hidden'); deleteButton.classList.remove('hidden'); toggleFields(); state.textContent=`Diperbarui ${new Date(post.updated_at).toLocaleString('id-ID')}`; dirty=false; loadPosts(id); autosize(); }
function toggleFields(){document.querySelector('#schedule-field').classList.toggle('hidden',field('status').value!=='scheduled');document.querySelector('#password-field').classList.toggle('hidden',field('access_level').value!=='password')}
function autosize(){document.querySelectorAll('.title-input,.subtitle-input').forEach(el=>{el.style.height='auto';el.style.height=`${el.scrollHeight}px`})}

editor.addEventListener('input', event => { dirty=true; state.textContent='Belum disimpan'; if(event.target===field('title')&&!currentId&&!field('slug').dataset.edited) field('slug').value=slugify(field('title').value); if(event.target===field('slug')) field('slug').dataset.edited='true'; autosize(); clearTimeout(saveTimer); if(currentId) saveTimer=setTimeout(()=>save(false),1800); });
field('status').addEventListener('change',toggleFields); field('access_level').addEventListener('change',toggleFields);
nav.addEventListener('click',event=>{const button=event.target.closest('[data-id]');if(button)loadPost(button.dataset.id)}); document.querySelector('#new-post').addEventListener('click',newPost);

async function save(showFeedback=true){ if(!field('title').value.trim()||!field('content').value.trim()){state.textContent='Judul dan isi wajib diisi';return} const locked=field('access_level').value==='password'; const password=field('article_password').value; const existing=posts.find(p=>p.id===currentId); if(locked&&!existing?.password_hash&&password.length<8){state.textContent='Password tulisan minimal 8 karakter';return} let publishedAt=null; if(field('status').value==='published') publishedAt=existing?.published_at||new Date().toISOString(); if(field('status').value==='scheduled') publishedAt=field('published_at').value?new Date(field('published_at').value).toISOString():null; if(field('status').value==='scheduled'&&!publishedAt){state.textContent='Pilih waktu terbit';return}
  const payload={author_id:user.id,title:field('title').value.trim(),subtitle:field('subtitle').value.trim(),slug:slugify(field('slug').value||field('title').value),excerpt:field('excerpt').value.trim(),category:field('category').value.trim()||'Catatan',tags:field('tags').value.split(',').map(v=>v.trim()).filter(Boolean),content:field('content').value,cover_url:field('cover_url').value||null,status:field('status').value,published_at:publishedAt,access_level:locked?(existing?.password_hash?'password':'public'):'public'};
  state.textContent='Menyimpan…'; let result; if(currentId) result=await supabase.from('blog_posts').update(payload).eq('id',currentId).select().single(); else result=await supabase.from('blog_posts').insert(payload).select().single(); if(result.error){state.textContent=`Gagal: ${result.error.message}`;return} currentId=result.data.id; if(locked&&password){const {error}=await supabase.rpc('blog_set_post_password',{requested_post_id:currentId,new_password:password});if(error){state.textContent=`Tulisan tersimpan, password gagal: ${error.message}`;return}} dirty=false; field('article_password').value=''; state.textContent=showFeedback?'Tersimpan ✓':'Tersimpan otomatis'; await loadPosts(currentId); if(!existing) loadPost(currentId); }
document.querySelector('#save-post').addEventListener('click',()=>save(true));
deleteButton.addEventListener('click',async()=>{if(!currentId||!confirm('Hapus tulisan ini secara permanen?'))return;const {error}=await supabase.from('blog_posts').delete().eq('id',currentId);if(error){state.textContent='Tulisan gagal dihapus';return}await loadPosts(null);newPost()});
document.querySelector('#sign-out').addEventListener('click',async()=>{await supabase.auth.signOut();location.reload()});

document.querySelector('.toolbar').addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;const area=field('content');const start=area.selectionStart,end=area.selectionEnd,selected=area.value.slice(start,end);let text;if(button.dataset.wrap)text=`${button.dataset.wrap}${selected||'teks'}${button.dataset.wrap}`;else if(button.dataset.prefix)text=`${button.dataset.prefix}${selected||'teks'}`;else if(button.dataset.link!==undefined)text=`[${selected||'teks tautan'}](https://)`;area.setRangeText(text,start,end,'end');area.dispatchEvent(new Event('input',{bubbles:true}));area.focus()});
document.querySelector('#cover-file').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;state.textContent='Mengunggah cover…';const path=`${user.id}/${Date.now()}-${file.name.toLowerCase().replace(/[^a-z0-9._-]+/g,'-')}`;const {error}=await supabase.storage.from('writing-media').upload(path,file,{upsert:false});if(error){state.textContent=`Upload gagal: ${error.message}`;return}const {data}=supabase.storage.from('writing-media').getPublicUrl(path);field('cover_url').value=data.publicUrl;const preview=document.querySelector('#cover-preview');preview.src=data.publicUrl;preview.classList.remove('hidden');dirty=true;state.textContent='Cover siap, simpan tulisan'});

window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue=''}});
const {data:{session}}=await supabase.auth.getSession(); if(session?.user?.email?.toLowerCase()===OWNER_EMAIL) await openStudio(session.user); else if(session) await supabase.auth.signOut();
